# Part - 1 Create Numpy Arrays:

In [1]:
import numpy as np

In [2]:
#Create an array of [1, 2, 3]. - 1 point

a1=np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
#Let x = [1, 2]. Convert it into an array. - 1 point

x=[1,2]
a2=np.array(x)
a2

array([1, 2])

In [4]:
#Create an 2D array with shape of (3,2), filled with ones. - 1 point
a3=np.ones((3,2),int)
a3

array([[1, 1],
       [1, 1],
       [1, 1]])

In [5]:
#Create a 3x3 2D array with ones on the diagonal and zeros elsewhere. - 1 point
a4=np.zeros((3,3),int)
np.fill_diagonal(a4,1)
a4

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [6]:
#Create an 2D array of 2 x 5 shape, filled with 6. - 1 point
a5=np.full((2,5),6)
a5

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

In [7]:
#Create an array of 2, 4, 6, 8, ..., 98, 100. - 1 point
a6=np.arange(2,101,2)
a6

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [8]:
#create (1) an array of 10 zeros; (2) an array of 10 fives. - 2 points
a71=np.zeros((10),int)
a71

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
a72=np.full((10),5)
a72

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [10]:
#create an 3x3x3 array filled with arbitrary values. - 1 points
a8=np.random.rand(3,3,3)
a8

array([[[5.86850714e-01, 2.22872665e-01, 7.34374598e-01],
        [1.07113893e-01, 5.78928267e-01, 1.09961189e-01],
        [3.50874359e-01, 9.90925691e-01, 5.42202542e-01]],

       [[6.25419548e-01, 3.83686038e-04, 4.62522855e-01],
        [4.27197236e-03, 1.03349118e-01, 2.29756945e-01],
        [1.14670450e-01, 2.51859404e-02, 9.92260692e-01]],

       [[1.13270707e-01, 2.59626802e-01, 9.62403710e-01],
        [2.33984155e-01, 9.01779065e-01, 4.24338376e-01],
        [5.99310229e-01, 1.22388906e-02, 1.73837727e-01]]])

In [51]:
# create a 3x4 2D array filled with values from 10 to 21 (inclusive). - 2 points
a9=np.random.randint(10,22,(3,4))
a9

array([[12, 17, 11, 20],
       [16, 20, 16, 10],
       [20, 17, 12, 13]])

In [50]:
a91=np.arange(10,22).reshape((3,4))
a91

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [12]:
#Create a numpy array of length 10, starting from 5 and has a step of 3 between consecutive numbers - 4 points
num=10
a10=np.linspace(5,5+(num*3),10,dtype=int,endpoint=False)
a10

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32])

# Part - 2 Operations on Numpy Arrays:

In [13]:
#Create an array of shape (3, 2) and populate it with random samples from a uniform distribution over [0, 1) and confirm you can get the same value when you run it next time. - 2 points
np.random.seed(0) 
b1 = np.random.uniform(0,1, size=(3,2))
b1

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318],
       [0.4236548 , 0.64589411]])

In [14]:
#Find the index of 5th repetition of number 1 in the given array x. - 4 points
#x: [1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2]
x=np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
b2=np.where(x==1)
b2[0][4]

8

In [15]:
#Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order. - 2 points
b3=np.arange(1,10)
b31,b32,b33=np.split(b3,[4,6])
b31,b32,b33

(array([1, 2, 3, 4]), array([5, 6]), array([7, 8, 9]))

In [16]:
'''
Given an array - 2 points
    [[ 0., 1., 2., 3.], [ 4., 5., 6., 7.], [ 8., 9., 10., 11.], [ 12., 13., 14., 15.]].
    Use np.split to split the array into left and right halves.
'''
x=np.arange(16.0).reshape(4, 4)
b41,b42=np.split(x, 2,axis=1)
b41,b42

(array([[ 0.,  1.],
        [ 4.,  5.],
        [ 8.,  9.],
        [12., 13.]]),
 array([[ 2.,  3.],
        [ 6.,  7.],
        [10., 11.],
        [14., 15.]]))

In [17]:
'''
Given an 2D array: [[5,10,15], [20,25,30], [35,40,45]] – 4 points
    (1) Slicing to get the sub-array [[10,15], [25,30]]
    (2) Getting individual element value "20"
'''
x=[[5,10,15], [20,25,30], [35,40,45]] 
b5=np.array(x)
b5[:2,1:]

array([[10, 15],
       [25, 30]])

In [18]:
b5[1,0]

20

In [19]:
'''
- 2 points:  Let x be an array [[ 1 2 3] [ 4 5 6]]. and y be an array [[ 7 8 9] [10 11 12]].
  Concatenate x and y so that a new array looks like
      [[1, 2, 3, 7, 8, 9],
        [4, 5, 6, 10, 11, 12]].
'''
x=np.array([[ 1, 2 ,3] ,[ 4 ,5 ,6]])
y=np.array([[ 7, 8 ,9], [10 ,11, 12]])
b6=np.concatenate([x,y],axis=1)
b6

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [20]:
'''
Compute the min/max (min is divided by max) for each row for given 2d numpy array, in which integer values range from 1 to 10 and shape is (5,3). - 6 points
      Require: the random seed is required to be 100.
'''
np.random.seed(100) 
x = np.random.randint(1,10, size=(5, 3)) 
b7max=np.amax(x,axis=1)
b7min=np.amin(x,axis=1)
b7=b7min/b7max
#b00=x.min(axis=1)/x.max(axis=1)
b7
#b00

array([0.44444444, 0.125     , 0.5       , 1.        , 0.11111111])

In [21]:
'''
Convert 3 arrays into a flat linear 1d array. - 2 points
     arr1: 0,1,2
     arr2: 3,4,5,6
     arr3: 7,8,9
     Generate the 3 arrays by numpy arange()
     Desired Output: array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
'''
b81=np.arange(0,3)
b82=np.arange(3,7)
b83=np.arange(7,10)
b8=np.concatenate((b81,b82,b83))
b8

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
'''
Get all items between 5 and 10 from a. - 4 points
    [2, 6, 1, 9, 10, 3, 27]
'''
a=np.array([2, 6, 1, 9, 10, 3, 27])
b9=a[np.where((a >= 5) & (a < 10))]
b9

array([6, 9])

In [23]:
'''
Get the positions where elements of a and b match. -2 points
    a: [1,2,3,2,3,4,3,4,5,6]
    b: [7,2,10,2,7,4,9,4,9,8]
'''
a=np.array([1,2,3,2,3,4,3,4,5,6])
b=np.array([7,2,10,2,7,4,9,4,9,8])
b10=np.where(a==b)
b10

(array([1, 3, 5, 7], dtype=int64),)

In [24]:
'''
Replace all odd numbers in arr with -1 without changing arr: - 4 points
    arr: ([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
'''
arr=np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
b11=arr.copy()
b11[b11%2!=0]=-1
b11

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [25]:
'''
Stack the arrays a and then b horizontally in order. - 4 points
    a is a 2x5 array with values from 0-9;
    b is a 2x5 array with the values are 1 uniformly.
'''
a=np.arange(10).reshape(2,5)
b=np.ones((2,5),int)
b12=np.hstack((a,b))
b12

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

# Part-3 Indexing and Slicing:

In [26]:
'''
1) Given a 1d array: [ 3, 6, 9, 25, 10, 8] - 6 points

        (1) To get all elements except the first:

        (2) To get all elements except the last:

        (3) To get every other element of the array (operation from the first element):

        (4) To get every element of the array except the first element:

        (5) To reverse the array:
'''
a=np.array([ 3, 6, 9, 25, 10, 8] )
a[1:]

array([ 6,  9, 25, 10,  8])

In [27]:
a[:-1]

array([ 3,  6,  9, 25, 10])

In [28]:
a[::2]

array([ 3,  9, 10])

In [29]:
a[1:]

array([ 6,  9, 25, 10,  8])

In [30]:
a[::-1]

array([ 8, 10, 25,  9,  6,  3])

Q2

In [31]:
'''
Multidimensional Arrays: 8 points

        (1) create an array with the components as 0-31 and the shape is (8,4). - 2 points

        (2) set the 3rd element in the 1st row to 0. - 2 points

        (3) the second column. - 2 points

        (4) Get the 3x3 region from the array: - 2 points
             ([ 9, 10, 11],
              [13, 14, 15],
              [17, 18, 19]])
'''
c2=np.arange(32).reshape(8,4)
c2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [32]:
c2[0,2]=0
c2

array([[ 0,  1,  0,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [33]:
c2[:,1]

array([ 1,  5,  9, 13, 17, 21, 25, 29])

In [34]:
c2[2:5,1:]

array([[ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19]])

Q3

In [35]:
'''
Create an 4x4 matrix in which 0 and 1 are staggered, with zeros on the main diagonal. Please use the numpy "slicing" method to realize. - 6 points
             [[0. 1. 0. 1.]
              [1. 0. 1. 0.]
              [0. 1. 0. 1.]
              [1. 0. 1. 0.]]
'''
c3=np.zeros((4,4))
c3[::2,1::2]=1
c3[1::2,::2]=1
c3

array([[0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.]])

Q4

In [36]:
'''
Subtract the 1d array b_1d from the 2d array a_2d, such that each item of b_1d subtracts from respective row of a_2d. - 4 points
        a_2d : [[3,3,3],[4,4,4],[5,5,5]]
        b_1d : [1,2,3]
        Desired Output: [[2 2 2] [2 2 2] [2 2 2]]
'''
b_1d=np.array([1,2,3])
a_2d=np.array([[3,3,3],[4,4,4],[5,5,5]])
a_2d-b_1d[:,None]

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [52]:
'''
Create a random array with 1000 elements and compute the average, variance, standard deviation of the array elements. - 7 points
And print the formatted outputs which keep 5 digits after the decimal point. Require: set the random seed as 100.
'''
np.random.seed(100) 
c5=np.random.rand(1,1000)
np.around(np.average(c5),5)

0.49818

In [53]:
np.around(np.var(c5),5)

0.08249

In [54]:
np.around(np.std(c5),5)

0.28722

Q5


In [40]:
'''
Write a 6x6 times table matrix: total 8 points
- by using numpy broadcasting (4 points)
- by using Python nested for-loop (4 points).
     Desired output:
        array([[ 1, 2, 3, 4, 5, 6],
                   [ 2, 4, 6, 8, 10, 12],
                   [ 3, 6, 9, 12, 15, 18],
                   [ 4, 8, 12, 16, 20, 24],
                   [ 5, 10, 15, 20, 25, 30],
                   [ 6, 12, 18, 24, 30, 36]])
'''
a=np.arange(1,7)
b=np.arange(1,7)
a[:, None] * b

array([[ 1,  2,  3,  4,  5,  6],
       [ 2,  4,  6,  8, 10, 12],
       [ 3,  6,  9, 12, 15, 18],
       [ 4,  8, 12, 16, 20, 24],
       [ 5, 10, 15, 20, 25, 30],
       [ 6, 12, 18, 24, 30, 36]])

In [41]:
a=[1,2,3,4,5,6]
res=[]
for i in range(6):
    res.append([x*(i+1) for x in a])
(res)
        

[[1, 2, 3, 4, 5, 6],
 [2, 4, 6, 8, 10, 12],
 [3, 6, 9, 12, 15, 18],
 [4, 8, 12, 16, 20, 24],
 [5, 10, 15, 20, 25, 30],
 [6, 12, 18, 24, 30, 36]]

Q6

In [42]:
'''
Broadcasting in Practice: Centering an array: 8 points
Imagine you have an array of 10 observations, each of which consists of 3 values(floating-point numbers). Store this in an array with the shape(10, 3). Seed is set as 100. - 2 points
Compute the mean of each feature using the mean aggregate across the first dimension; - 2 points
Center the X array by subtracting the mean; - 2 points
Double-check the correctness of the centralization using the mean aggregate again (check that the centered array has near zero mean). - 2 points
'''
np.random.seed(100) 
c6=np.random.rand(10,3)
c6

array([[0.54340494, 0.27836939, 0.42451759],
       [0.84477613, 0.00471886, 0.12156912],
       [0.67074908, 0.82585276, 0.13670659],
       [0.57509333, 0.89132195, 0.20920212],
       [0.18532822, 0.10837689, 0.21969749],
       [0.97862378, 0.81168315, 0.17194101],
       [0.81622475, 0.27407375, 0.43170418],
       [0.94002982, 0.81764938, 0.33611195],
       [0.17541045, 0.37283205, 0.00568851],
       [0.25242635, 0.79566251, 0.01525497]])

In [43]:
cmean=c6.mean(0)
cmean

array([0.59820669, 0.51805407, 0.20723935])

In [44]:
ccen=c6-cmean
ccen

array([[-0.05480175, -0.23968468,  0.21727824],
       [ 0.24656945, -0.51333521, -0.08567023],
       [ 0.0725424 ,  0.30779869, -0.07053276],
       [-0.02311336,  0.37326789,  0.00196277],
       [-0.41287847, -0.40967718,  0.01245814],
       [ 0.3804171 ,  0.29362908, -0.03529834],
       [ 0.21801806, -0.24398032,  0.22446483],
       [ 0.34182313,  0.29959531,  0.1288726 ],
       [-0.42279623, -0.14522202, -0.20155085],
       [-0.34578033,  0.27760844, -0.19198438]])

In [45]:
ccen.mean(0)

array([ 3.33066907e-17,  0.00000000e+00, -1.66533454e-17])